<?php

class ETC_CmsNavigationMenu_Widget extends Elementor_Theme_Core_Widget_Base{
    protected $name = 'cms_navigation_menu';
    protected $title = 'Navigation Menu';
    protected $icon = 'eicon-menu-bar';
    protected $categories = array( 'elementor-theme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost:8888\/medcity\/wp-content\/themes\/medcity\/elementor\/templates\/widgets\/cms_navigation_menu\/layout\/1.webp"},"2":{"label":"Layout 2","image":"http:\/\/localhost:8888\/medcity\/wp-content\/themes\/medcity\/elementor\/templates\/widgets\/cms_navigation_menu\/layout\/2.webp"},"3":{"label":"Layout 3","image":"http:\/\/localhost:8888\/medcity\/wp-content\/themes\/medcity\/elementor\/templates\/widgets\/cms_navigation_menu\/layout\/3.webp"}}}]},{"name":"source_section","label":"Source Settings","tab":"content","controls":[{"name":"widget_title","label":"Widget Title","type":"textarea","label_block":true},{"name":"widget_title_class","label":"Widget Title CSS Class","type":"text","label_block":true,"condition":{"widget_title!":""}},{"name":"menu","label":"Select Menu","type":"select","options":{"departments":"Departments","footer-policy":"Footer Policy","main-menu-long":"Main Menu Long","main-menu-short":"Main Menu Short","menu-help":"Menu Help","menu-link":"Menu Link","menu-solutions":"Menu Solutions","services-menu":"Services Menu"},"separator":"before"},{"name":"style","label":"Style","type":"select","options":{"default":"Default","inline":"Inline","e-sidebar-widget":"Sidebar Menu"},"default":"default","condition":{"layout":["1"]}},{"name":"link_color","label":"Link Color","type":"color","selectors":{"{{WRAPPER}} .cms-navigation-menu ul.menu li a":"color: {{VALUE}} !important;"}},{"name":"link_color_hover","label":"Link Color Hover &amp; Active","type":"color","selectors":{"{{WRAPPER}} .cms-navigation-menu ul.menu li a:hover, {{WRAPPER}} .cms-navigation-menu ul.menu li.current_page_item > a":"color: {{VALUE}} !important;"}},{"name":"border_color_hover","label":"Border Color Hover &amp; Active","type":"color","condition":{"style":["inline","one-page"]},"selectors":{"{{WRAPPER}} .cms-navigation-menu.inline ul.menu > li > a:after":"background-color: {{VALUE}} !important;"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}