<?php

class ETC_CmsWorkProcess_Widget extends Elementor_Theme_Core_Widget_Base{
    protected $name = 'cms_work_process';
    protected $title = 'Work Process';
    protected $icon = 'eicon-toggle';
    protected $categories = array( 'elementor-theme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost:8888\/medcity\/wp-content\/themes\/medcity\/elementor\/templates\/widgets\/cms_work_process\/layout-image\/layout1.jpg"}}}]},{"name":"section_tabs","label":"Tabs","tab":"content","controls":[{"name":"wg_subtitle","label":"Widget Sub Title","type":"text","default":"","label_block":true},{"name":"wg_title","label":"Widget Title","type":"textarea","default":"","rows":5,"show_label":false},{"name":"tabs","label":"Tabs Items","type":"repeater","controls":[{"name":"tab_title","label":"Title","type":"text","default":"Tab Title","placeholder":"Tab Title","label_block":true},{"name":"tab_description","label":"Description","type":"textarea","default":"Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.","placeholder":"Enter your description","rows":6,"show_label":false},{"name":"content_type","label":"Content Type","type":"select","default":"text_editor","options":{"text_editor":"Text Editor","template":"Template"}},{"name":"tab_content","label":"Content","type":"wysiwyg","default":"Tab Content","placeholder":"Tab Content","show_label":false,"condition":{"content_type":"text_editor"}},{"name":"tab_content_template","label":"Template","type":"select","default":"","options":{"":"Select Template","13250":"mapfff","13186":"icon list","13164":"h7_form_hear","13145":"Doctor Grid","13074":"h7_222","12868":"1111","12197":"sign","11759":"Default Kit","11758":"Default Kit"},"condition":{"content_type":"template"}}],"title_field":"{{{ tab_title }}}"}]},{"name":"section_style_tab","label":"Style","tab":"style","controls":[{"name":"tab_background","label":"Tab Background","type":"color","selectors":{"{{WRAPPER}} .cms-tabs .cms-tab-title":"background-color: {{VALUE}};"}},{"name":"tab_color","label":"Tab Color","type":"color","selectors":{"{{WRAPPER}} .cms-tabs .cms-tab-title":"color: {{VALUE}};","{{WRAPPER}} .cms-tabs .cms-tab-title svg":"fill: {{VALUE}};"}},{"name":"tab_active_background","label":"Tab Active Background","type":"color","selectors":{"{{WRAPPER}} .cms-tabs .cms-tab-title.active":"background-color: {{VALUE}};"}},{"name":"tab_active_color","label":"Tab Active Color","type":"color","selectors":{"{{WRAPPER}} .cms-tabs .cms-tab-title.active":"color: {{VALUE}};","{{WRAPPER}} .cms-tabs .cms-tab-title.active svg":"fill: {{VALUE}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'cms-tabs-widget-js' );
}