<?php

class ETC_CmsImageGallery_Widget extends Elementor_Theme_Core_Widget_Base{
    protected $name = 'cms_image_gallery';
    protected $title = 'Image Gallery';
    protected $icon = 'eicon-gallery-grid';
    protected $categories = array( 'elementor-theme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost:8888\/medcity\/wp-content\/themes\/medcity\/elementor\/templates\/widgets\/cms_image_gallery\/layout-image\/layout1.jpg"}}}]},{"name":"grid_section","label":"Image Gallery","tab":"content","controls":[{"name":"wp_gallery","label":"Add Images","type":"gallery","show_label":false,"dynamic":{"active":true}},{"name":"thumbnail","type":"image-size","control_type":"group","default":"full"},{"name":"col_xs","label":"Columns XS Devices","type":"select","default":"1","options":{"1":"1","2":"2","3":"3","4":"4","6":"6"}},{"name":"col_sm","label":"Columns SM Devices","type":"select","default":"1","options":{"1":"1","2":"2","3":"3","4":"4","6":"6"}},{"name":"col_md","label":"Columns MD Devices","type":"select","default":"2","options":{"1":"1","2":"2","3":"3","4":"4","6":"6"}},{"name":"col_lg","label":"Columns LG Devices","type":"select","default":"3","options":{"1":"1","2":"2","3":"3","4":"4","6":"6"}},{"name":"col_xl","label":"Columns XL Devices","type":"select","default":"3","options":{"1":"1","2":"2","3":"3","4":"4","6":"6"}},{"name":"gallery_rand","label":"Order By","type":"select","options":{"":"Default","rand":"Random"},"default":""}]},{"name":"gallery_images_section","label":"Images","tab":"style","controls":[{"name":"gap","label":"Image Gap","type":"number","control_type":"responsive","default":15,"selectors":{"{{WRAPPER}} .cms-grid .cms-grid-inner":"margin-left: -{{VALUE}}px; margin-right: -{{VALUE}}px;","{{WRAPPER}} .cms-grid .grid-item":"padding-left: {{VALUE}}px; padding-right: {{VALUE}}px; margin-top: {{VALUE}}px; margin-bottom: {{VALUE}}px;","{{WRAPPER}} .cms-grid .grid-sizer":"padding-left: {{VALUE}}px; padding-right: {{VALUE}}px;"}}]},{"name":"caption_section","label":"Caption","tab":"style","controls":[{"name":"gallery_display_caption","label":"Display","type":"select","default":"none","options":{"none":"Hide","":"Show"},"selectors":{"{{WRAPPER}} .grid-item .image-caption":"display: {{VALUE}};"}},{"name":"caption_align","label":"Alignment","type":"choose","options":{"left":{"title":"Left","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"right":{"title":"Right","icon":"eicon-text-align-right"}},"default":"center","selectors":{"{{WRAPPER}} .grid-item .image-caption":"text-align: {{VALUE}};"},"condition":{"gallery_display_caption":""}},{"name":"caption_color","label":"Text Color","type":"color","default":"","selectors":{"{{WRAPPER}} .grid-item .image-caption":"color: {{VALUE}};"},"condition":{"gallery_display_caption":""}},{"name":"caption_typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .grid-item .image-caption","condition":{"gallery_display_caption":""}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'imagesloaded','isotope','cms-post-grid-widget-js' );
}