<?php

class ETC_CmsImageBoxCarousel_Widget extends Elementor_Theme_Core_Widget_Base{
    protected $name = 'cms_image_box_carousel';
    protected $title = 'Image Box Carousel';
    protected $icon = 'eicon-info-box';
    protected $categories = array( 'elementor-theme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost:8888\/medcity\/wp-content\/themes\/medcity\/elementor\/templates\/widgets\/cms_image_box_carousel\/layout-image\/layout1.jpg"}}}]},{"name":"section_boxs","label":"Box Settings","tab":"content","controls":[{"name":"boxs","label":"","type":"repeater","default":[],"controls":[{"name":"box_image","label":"Box Image","type":"media","label_block":true},{"name":"box_text","label":"Box Text","type":"textarea","label_block":true,"default":""}]}]},{"name":"section_carousel_settings","label":"Carousel Settings","tab":"settings","controls":[{"name":"content_style","label":"Content Style","type":"select","options":{"vertical":"Vertical","horizontal":"Horizontal"},"default":"vertical"},{"name":"dots","label":"Show Dots","type":"switcher"},{"name":"pause_on_hover","label":"Pause on Hover","type":"switcher"},{"name":"autoplay","label":"Autoplay","type":"switcher"},{"name":"autoplay_speed","label":"Autoplay Speed","type":"number","default":5000,"condition":{"autoplay":"true"}},{"name":"infinite","label":"Infinite Loop","type":"switcher"},{"name":"speed","label":"Animation Speed","type":"number","default":500},{"name":"text_color","label":"Box Text Color","type":"color","selectors":{"{{WRAPPER}} .cms-image-box-carousel .cms-box-inner .box-text h4":"color: {{VALUE}};"}},{"name":"box_background","label":"Box Background","type":"color","selectors":{"{{WRAPPER}} .cms-image-box-carousel":"background-color: {{VALUE}};"}},{"name":"box_border_radius","label":"Box Border Radius","type":"dimensions","size_units":["px","%"],"selectors":{"{{WRAPPER}} .cms-image-box-carousel":"border-radius: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'jquery-slick','cms-clients-list-widget-js' );
}